apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm-container
        image: us-east1-docker.pkg.dev/dogfood-cx/registryrepository/litellm-database:main-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-bedrock-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-bedrock-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: LITELLM_MASTER_KEY
          value: "sk-1234"
        args:
        - "--detailed_debug"
        - "--config"
        - "/config/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health/liveliness
            port: 4000
          initialDelaySeconds: 120
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 4000
          initialDelaySeconds: 120
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "1Gi"
      volumes:
      - name: config-volume
        configMap:
          name: litellm-config
